# Normalize the UCDP/PRIO Armed Conflict dataset

In [1]:
import pandas as pd
import numpy as np

In [2]:
pd.set_option('display.max_rows', 20)
pd.set_option('display.max_columns', 50)

In [3]:
df = pd.read_csv("../Data/UCDP_PRIO/ucdpprio_armedconflict_api.csv")
#actors = pd.read_csv("../Data/UCDP_PRIO/Raw/actorlist.csv", usecols=['ActorID', 'Name'], encoding='utf-8')
#actors_tr = pd.read_csv("../Data/UCDP_PRIO/Raw/translate_actor.csv", usecols=['new_id', 'name'], encoding='utf-8')

In [4]:
df.columns

Index(['conflict_id', 'cumulative_intensity', 'ep_end', 'ep_end_date',
       'ep_end_prec', 'gwno_a', 'gwno_a_2nd', 'gwno_b', 'gwno_b_2nd',
       'gwno_loc', 'incompatibility', 'intensity_level', 'location', 'region',
       'side_a', 'side_a_2nd', 'side_a_id', 'side_b', 'side_b_2nd',
       'side_b_id', 'start_date', 'start_date2', 'start_prec', 'start_prec2',
       'territory_name', 'type_of_conflict', 'version', 'year'],
      dtype='object')

In [5]:
df

conflict_id  cumulative_intensity  ep_end ep_end_date  ep_end_prec  \
0             200                     1       1  1946-07-21          NaN   
1             200                     1       1  1952-04-12          NaN   
2             200                     1       1  1967-10-16          NaN   
3             201                     0       0         NaN          NaN   
4             201                     0       0         NaN          NaN   
...           ...                   ...     ...         ...          ...   
2379        14275                     1       0         NaN          NaN   
2380        14333                     0       1  2016-11-09          NaN   
2381        14113                     0       0         NaN          NaN   
2382        14113                     0       0         NaN          NaN   
2383        14609                     0       0         NaN          NaN   

     gwno_a                                         gwno_a_2nd gwno_b  \
0       145                                                NaN    NaN   
1       145                                                NaN    NaN   
2       145                                                NaN    NaN   
3       220                                                NaN    NaN   
4       220                                                NaN    NaN   
...     ...                                                ...    ...   
2379    840                                                NaN    NaN   
2380    616                                                NaN    NaN   
2381    432  371, 305, 771, 211, 434, 760, 346, 439, 516, 8...    NaN   
2382    432  371, 305, 771, 211, 434, 760, 346, 439, 516, 8...    NaN   
2383    630                                                NaN    666   

     gwno_b_2nd  gwno_loc  incompatibility  intensity_level  \
0           NaN       145                2                2   
1           NaN       145                2                1   
2           NaN       145                2                1   
3           NaN       811                1                1   
4           NaN       811                1                1   
...         ...       ...              ...              ...   
2379        NaN       840                1                1   
2380        NaN       616                1                1   
2381        NaN       432                1                1   
2382        NaN       432                1                1   
2383        NaN  630, 666                2                1   

                  location region                     side_a  \
0                  Bolivia      5      Government of Bolivia   
1                  Bolivia      5      Government of Bolivia   
2                  Bolivia      5      Government of Bolivia   
3     Cambodia (Kampuchea)      3       Government of France   
4     Cambodia (Kampuchea)      3       Government of France   
...                    ...    ...                        ...   
2379           Philippines      3  Government of Philippines   
2380               Tunisia      4      Government of Tunisia   
2381                  Mali      4         Government of Mali   
2382                  Mali      4         Government of Mali   
2383          Iran, Israel      2         Government of Iran   

                                             side_a_2nd side_a_id  \
0                                                   NaN        23   
1                                                   NaN        23   
2                                                   NaN        23   
3                                                   NaN        33   
4                                                   NaN        33   
...                                                 ...       ...   
2379                                                NaN       154   
2380                                                NaN       110   
2381  Government of Armenia, Government of Austria, ...        72   


In [6]:
# convert date columns to date datatype and drop version column
df['start_date'] = pd.to_datetime(df['start_date'], format = '%Y-%m-%d')
df['start_date2'] = pd.to_datetime(df['start_date2'], format = '%Y-%m-%d')
df['ep_end_date'] = pd.to_datetime(df['ep_end_date'], format = '%Y-%m-%d')
df = df.drop(columns=['version'])

## create observation ids

each row/observation is a conflict-year

In [7]:
df['obs_id'] = df['conflict_id'].astype(str) + '-' + df['year'].astype(str)
df

conflict_id  cumulative_intensity  ep_end ep_end_date  ep_end_prec  \
0             200                     1       1  1946-07-21          NaN   
1             200                     1       1  1952-04-12          NaN   
2             200                     1       1  1967-10-16          NaN   
3             201                     0       0         NaT          NaN   
4             201                     0       0         NaT          NaN   
...           ...                   ...     ...         ...          ...   
2379        14275                     1       0         NaT          NaN   
2380        14333                     0       1  2016-11-09          NaN   
2381        14113                     0       0         NaT          NaN   
2382        14113                     0       0         NaT          NaN   
2383        14609                     0       0         NaT          NaN   

     gwno_a                                         gwno_a_2nd gwno_b  \
0       145                                                NaN    NaN   
1       145                                                NaN    NaN   
2       145                                                NaN    NaN   
3       220                                                NaN    NaN   
4       220                                                NaN    NaN   
...     ...                                                ...    ...   
2379    840                                                NaN    NaN   
2380    616                                                NaN    NaN   
2381    432  371, 305, 771, 211, 434, 760, 346, 439, 516, 8...    NaN   
2382    432  371, 305, 771, 211, 434, 760, 346, 439, 516, 8...    NaN   
2383    630                                                NaN    666   

     gwno_b_2nd  gwno_loc  incompatibility  intensity_level  \
0           NaN       145                2                2   
1           NaN       145                2                1   
2           NaN       145                2                1   
3           NaN       811                1                1   
4           NaN       811                1                1   
...         ...       ...              ...              ...   
2379        NaN       840                1                1   
2380        NaN       616                1                1   
2381        NaN       432                1                1   
2382        NaN       432                1                1   
2383        NaN  630, 666                2                1   

                  location region                     side_a  \
0                  Bolivia      5      Government of Bolivia   
1                  Bolivia      5      Government of Bolivia   
2                  Bolivia      5      Government of Bolivia   
3     Cambodia (Kampuchea)      3       Government of France   
4     Cambodia (Kampuchea)      3       Government of France   
...                    ...    ...                        ...   
2379           Philippines      3  Government of Philippines   
2380               Tunisia      4      Government of Tunisia   
2381                  Mali      4         Government of Mali   
2382                  Mali      4         Government of Mali   
2383          Iran, Israel      2         Government of Iran   

                                             side_a_2nd side_a_id  \
0                                                   NaN        23   
1                                                   NaN        23   
2                                                   NaN        23   
3                                                   NaN        33   
4                                                   NaN        33   
...                                                 ...       ...   
2379                                                NaN       154   
2380                                                NaN       110   
2381  Government of Armenia, Government of Austria, ...        72   


## create episode ids

Conflicts have multiple episodes when a conflict calms down to <25 deaths in a year (and therefore is not recorded as an observation) and the flares up again to >25 deaths in a year (and therefore has another observation). This can happen multiple times.

In [8]:
episode_groups = df.groupby('conflict_id').agg({'start_date2': 'nunique'})

In [9]:
def make_num_list(x):
    num_list = [1]
    start = 1
    while start < x:
        start += 1
        num_list.append(start)
    return num_list

episode_groups['num_list'] = episode_groups['start_date2'].apply(make_num_list)
episode_groups

start_date2   num_list
conflict_id                        
200                    3  [1, 2, 3]
201                    1        [1]
202                    1        [1]
203                    1        [1]
204                    1        [1]
...                  ...        ...
14129                  1        [1]
14268                  1        [1]
14275                  1        [1]
14333                  1        [1]
14609                  1        [1]

[286 rows x 2 columns]

In [10]:
episode_ids = episode_groups.num_list.apply(pd.Series).reset_index() \
    .melt(id_vars = ['conflict_id']) \
    .drop(columns=['variable']) \
    .dropna() \
    .sort_values(by=['conflict_id', 'value']) \
    .astype({'value': 'int'}) \
    .reset_index(drop=True)

episode_ids['ep_id'] = episode_ids['conflict_id'].astype(str) + "-" + episode_ids['value'].astype(str)
episode_ids = episode_ids.rename(columns={'value':'episode'})
episode_ids = episode_ids.sort_values(by=['conflict_id', 'episode']).reset_index(drop=True)
episode_ids

conflict_id  episode    ep_id
0            200        1    200-1
1            200        2    200-2
2            200        3    200-3
3            201        1    201-1
4            202        1    202-1
..           ...      ...      ...
553        14129        1  14129-1
554        14268        1  14268-1
555        14275        1  14275-1
556        14333        1  14333-1
557        14609        1  14609-1

[558 rows x 3 columns]

In [11]:
episode_groups2 = df[['conflict_id', 'start_date2']].drop_duplicates().reset_index(drop=True)
episode_groups2['start_date2'] = pd.to_datetime(episode_groups2['start_date2'], format = '%Y-%m-%d')
episode_groups2 = episode_groups2.sort_values(by=['conflict_id', 'start_date2']).reset_index(drop=True)
episode_groups2 = episode_groups2.rename(columns={'conflict_id':'conflict_id2'})
episode_groups2

conflict_id2 start_date2
0             200  1946-07-21
1             200  1952-04-09
2             200  1967-03-31
3             201  1946-08-31
4             202  1946-12-31
..            ...         ...
553         14129  2017-12-08
554         14268  2017-06-11
555         14275  2016-06-01
556         14333  2016-03-07
557         14609  2018-04-29

[558 rows x 2 columns]

In [12]:
episode_groups3 = pd.concat([episode_ids, episode_groups2], axis=1)
episode_groups3

conflict_id  episode    ep_id  conflict_id2 start_date2
0            200        1    200-1           200  1946-07-21
1            200        2    200-2           200  1952-04-09
2            200        3    200-3           200  1967-03-31
3            201        1    201-1           201  1946-08-31
4            202        1    202-1           202  1946-12-31
..           ...      ...      ...           ...         ...
553        14129        1  14129-1         14129  2017-12-08
554        14268        1  14268-1         14268  2017-06-11
555        14275        1  14275-1         14275  2016-06-01
556        14333        1  14333-1         14333  2016-03-07
557        14609        1  14609-1         14609  2018-04-29

[558 rows x 5 columns]

In [13]:
episode_groups3[episode_groups3['conflict_id'] != episode_groups3['conflict_id2']]

Empty DataFrame
Columns: [conflict_id, episode, ep_id, conflict_id2, start_date2]
Index: []

In [14]:
episode_groups3 = episode_groups3.drop(columns=['conflict_id2'])

In [15]:
df = df.merge(episode_groups3, on=['conflict_id', 'start_date2'])
df

conflict_id  cumulative_intensity  ep_end ep_end_date  ep_end_prec  \
0             200                     1       1  1946-07-21          NaN   
1             200                     1       1  1952-04-12          NaN   
2             200                     1       1  1967-10-16          NaN   
3             201                     0       0         NaT          NaN   
4             201                     0       0         NaT          NaN   
...           ...                   ...     ...         ...          ...   
2379        14275                     1       0         NaT          NaN   
2380        14333                     0       1  2016-11-09          NaN   
2381        14113                     0       0         NaT          NaN   
2382        14113                     0       0         NaT          NaN   
2383        14609                     0       0         NaT          NaN   

     gwno_a                                         gwno_a_2nd gwno_b  \
0       145                                                NaN    NaN   
1       145                                                NaN    NaN   
2       145                                                NaN    NaN   
3       220                                                NaN    NaN   
4       220                                                NaN    NaN   
...     ...                                                ...    ...   
2379    840                                                NaN    NaN   
2380    616                                                NaN    NaN   
2381    432  371, 305, 771, 211, 434, 760, 346, 439, 516, 8...    NaN   
2382    432  371, 305, 771, 211, 434, 760, 346, 439, 516, 8...    NaN   
2383    630                                                NaN    666   

     gwno_b_2nd  gwno_loc  incompatibility  intensity_level  \
0           NaN       145                2                2   
1           NaN       145                2                1   
2           NaN       145                2                1   
3           NaN       811                1                1   
4           NaN       811                1                1   
...         ...       ...              ...              ...   
2379        NaN       840                1                1   
2380        NaN       616                1                1   
2381        NaN       432                1                1   
2382        NaN       432                1                1   
2383        NaN  630, 666                2                1   

                  location region                     side_a  \
0                  Bolivia      5      Government of Bolivia   
1                  Bolivia      5      Government of Bolivia   
2                  Bolivia      5      Government of Bolivia   
3     Cambodia (Kampuchea)      3       Government of France   
4     Cambodia (Kampuchea)      3       Government of France   
...                    ...    ...                        ...   
2379           Philippines      3  Government of Philippines   
2380               Tunisia      4      Government of Tunisia   
2381                  Mali      4         Government of Mali   
2382                  Mali      4         Government of Mali   
2383          Iran, Israel      2         Government of Iran   

                                             side_a_2nd side_a_id  \
0                                                   NaN        23   
1                                                   NaN        23   
2                                                   NaN        23   
3                                                   NaN        33   
4                                                   NaN        33   
...                                                 ...       ...   
2379                                                NaN       154   
2380                                                NaN       110   
2381  Government of Armenia, Government of Austria, ...        72   


## Adjust column values and create new columns as needed

shift conflict type to match correlates of war conflict types

In [16]:
df['type_of_conflict'].unique()

array([3, 1, 4, 2])

In [17]:
df['isInternational'] = np.nan
df['isInternational'] [df['type_of_conflict'] == 4] = 1
df['isInternational'] [df['type_of_conflict'] == 3] = 0
df['isInternational'] = df['isInternational'].astype('Int64')

/usr/local/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  
/usr/local/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until


In [18]:
type_dict = {1: "Extrasystemic", 2: "Interstate", 3: "Internal", 4: "Internal"}
df['type_of_conflict'] = df['type_of_conflict'].replace(type_dict)

intensity_dict = {1: "Minor", 2: "War"}
df['intensity_level'] = df['intensity_level'].replace(intensity_dict)

cum_intensity_dict = {0: "Minor", 1: "War"}
df['cumulative_intensity'] = df['cumulative_intensity'].replace(cum_intensity_dict)

create incompatibility flags

In [19]:
df['incompatibility'].unique()

array([2, 1, 3])

In [20]:
df['incompatibility_isTerritory'] = 1
df['incompatibility_isTerritory'] [df['incompatibility'] == 2] = 0

df['incompatibility_isGovernment'] = 1
df['incompatibility_isGovernment'] [df['incompatibility'] == 1] = 0

/usr/local/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  
/usr/local/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """


In [21]:
df

conflict_id cumulative_intensity  ep_end ep_end_date  ep_end_prec  \
0             200                  War       1  1946-07-21          NaN   
1             200                  War       1  1952-04-12          NaN   
2             200                  War       1  1967-10-16          NaN   
3             201                Minor       0         NaT          NaN   
4             201                Minor       0         NaT          NaN   
...           ...                  ...     ...         ...          ...   
2379        14275                  War       0         NaT          NaN   
2380        14333                Minor       1  2016-11-09          NaN   
2381        14113                Minor       0         NaT          NaN   
2382        14113                Minor       0         NaT          NaN   
2383        14609                Minor       0         NaT          NaN   

     gwno_a                                         gwno_a_2nd gwno_b  \
0       145                                                NaN    NaN   
1       145                                                NaN    NaN   
2       145                                                NaN    NaN   
3       220                                                NaN    NaN   
4       220                                                NaN    NaN   
...     ...                                                ...    ...   
2379    840                                                NaN    NaN   
2380    616                                                NaN    NaN   
2381    432  371, 305, 771, 211, 434, 760, 346, 439, 516, 8...    NaN   
2382    432  371, 305, 771, 211, 434, 760, 346, 439, 516, 8...    NaN   
2383    630                                                NaN    666   

     gwno_b_2nd  gwno_loc  incompatibility intensity_level  \
0           NaN       145                2             War   
1           NaN       145                2           Minor   
2           NaN       145                2           Minor   
3           NaN       811                1           Minor   
4           NaN       811                1           Minor   
...         ...       ...              ...             ...   
2379        NaN       840                1           Minor   
2380        NaN       616                1           Minor   
2381        NaN       432                1           Minor   
2382        NaN       432                1           Minor   
2383        NaN  630, 666                2           Minor   

                  location region                     side_a  \
0                  Bolivia      5      Government of Bolivia   
1                  Bolivia      5      Government of Bolivia   
2                  Bolivia      5      Government of Bolivia   
3     Cambodia (Kampuchea)      3       Government of France   
4     Cambodia (Kampuchea)      3       Government of France   
...                    ...    ...                        ...   
2379           Philippines      3  Government of Philippines   
2380               Tunisia      4      Government of Tunisia   
2381                  Mali      4         Government of Mali   
2382                  Mali      4         Government of Mali   
2383          Iran, Israel      2         Government of Iran   

                                             side_a_2nd side_a_id  \
0                                                   NaN        23   
1                                                   NaN        23   
2                                                   NaN        23   
3                                                   NaN        33   
4                                                   NaN        33   
...                                                 ...       ...   
2379                                                NaN       154   
2380                                                NaN       110   
2381  Government of Armenia, Government of Austria, ...        72   
2382  Government of Arme

create conflict end date based on last episode end date

In [22]:
ongoing = df[(df.year == 2018) & (df.ep_end == 0)].conflict_id.tolist()

In [23]:
conflict_enddates = df.groupby('conflict_id').agg({'ep_end_date':'max'})
conflict_enddates = conflict_enddates.reset_index().rename(columns={'ep_end_date':'end_date'})
conflict_enddates['end_date'] [conflict_enddates.conflict_id.isin(ongoing)] = pd.NaT
conflict_enddates

/usr/local/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until


conflict_id   end_date
0            200 1967-10-16
1            201 1953-11-09
2            202 1949-12-08
3            203 1949-10-16
4            204 1949-08-15
..           ...        ...
281        14129        NaT
282        14268 2017-06-11
283        14275        NaT
284        14333 2016-11-09
285        14609        NaT

[286 rows x 2 columns]

In [24]:
df = df.merge(conflict_enddates, on='conflict_id', how='left')
df

conflict_id cumulative_intensity  ep_end ep_end_date  ep_end_prec  \
0             200                  War       1  1946-07-21          NaN   
1             200                  War       1  1952-04-12          NaN   
2             200                  War       1  1967-10-16          NaN   
3             201                Minor       0         NaT          NaN   
4             201                Minor       0         NaT          NaN   
...           ...                  ...     ...         ...          ...   
2379        14275                  War       0         NaT          NaN   
2380        14333                Minor       1  2016-11-09          NaN   
2381        14113                Minor       0         NaT          NaN   
2382        14113                Minor       0         NaT          NaN   
2383        14609                Minor       0         NaT          NaN   

     gwno_a                                         gwno_a_2nd gwno_b  \
0       145                                                NaN    NaN   
1       145                                                NaN    NaN   
2       145                                                NaN    NaN   
3       220                                                NaN    NaN   
4       220                                                NaN    NaN   
...     ...                                                ...    ...   
2379    840                                                NaN    NaN   
2380    616                                                NaN    NaN   
2381    432  371, 305, 771, 211, 434, 760, 346, 439, 516, 8...    NaN   
2382    432  371, 305, 771, 211, 434, 760, 346, 439, 516, 8...    NaN   
2383    630                                                NaN    666   

     gwno_b_2nd  gwno_loc  incompatibility intensity_level  \
0           NaN       145                2             War   
1           NaN       145                2           Minor   
2           NaN       145                2           Minor   
3           NaN       811                1           Minor   
4           NaN       811                1           Minor   
...         ...       ...              ...             ...   
2379        NaN       840                1           Minor   
2380        NaN       616                1           Minor   
2381        NaN       432                1           Minor   
2382        NaN       432                1           Minor   
2383        NaN  630, 666                2           Minor   

                  location region                     side_a  \
0                  Bolivia      5      Government of Bolivia   
1                  Bolivia      5      Government of Bolivia   
2                  Bolivia      5      Government of Bolivia   
3     Cambodia (Kampuchea)      3       Government of France   
4     Cambodia (Kampuchea)      3       Government of France   
...                    ...    ...                        ...   
2379           Philippines      3  Government of Philippines   
2380               Tunisia      4      Government of Tunisia   
2381                  Mali      4         Government of Mali   
2382                  Mali      4         Government of Mali   
2383          Iran, Israel      2         Government of Iran   

                                             side_a_2nd side_a_id  \
0                                                   NaN        23   
1                                                   NaN        23   
2                                                   NaN        23   
3                                                   NaN        33   
4                                                   NaN        33   
...                                                 ...       ...   
2379                                                NaN       154   
2380                                                NaN       110   
2381  Government of Armenia, Government of Austria, ...        72   
2382  Government of Arme

## Find columns that are functionally dependent on 'conflict_id' for the CONFLICT table

- 'incompatibility'
- 'territory_name'
- 'region' (multivalued)
- 'start_date'
- 'start_prec'
- 'end_date'
- 'type_of_conflict' (after revising so 3 and 4 are both "Internal")
- 'location' (multivalued)
- 'gwno_loc' (multivalued)
- 'gwno_a' (multivalued)
- 'side_a' (multivalued)
- 'side_a_id' (multivalued)

note: 'gwno_b' corresponds to 'side_b', which is not dependent on the conflict id. However, 'gwno_b' is only present if 'side_b' is a state, and thus 'gwno_b' is often missing. It seems like it is functionally dependent on 'conflict_id', but this is misleading.

In [25]:
df.columns

Index(['conflict_id', 'cumulative_intensity', 'ep_end', 'ep_end_date',
       'ep_end_prec', 'gwno_a', 'gwno_a_2nd', 'gwno_b', 'gwno_b_2nd',
       'gwno_loc', 'incompatibility', 'intensity_level', 'location', 'region',
       'side_a', 'side_a_2nd', 'side_a_id', 'side_b', 'side_b_2nd',
       'side_b_id', 'start_date', 'start_date2', 'start_prec', 'start_prec2',
       'territory_name', 'type_of_conflict', 'year', 'obs_id', 'episode',
       'ep_id', 'isInternational', 'incompatibility_isTerritory',
       'incompatibility_isGovernment', 'end_date'],
      dtype='object')

In [26]:
df.groupby('conflict_id')['incompatibility'].nunique().unique()

array([1])

In [27]:
df.groupby('conflict_id')['territory_name'].nunique().unique()

array([0, 1])

In [28]:
df.groupby('conflict_id')['region'].nunique().unique()

array([1])

In [29]:
df.groupby('conflict_id')['start_date'].nunique().unique()

array([1])

In [30]:
df.groupby('conflict_id')['start_prec'].nunique().unique()

array([1])

In [31]:
df.groupby('conflict_id')['location'].nunique().unique()

array([1])

In [32]:
df.groupby('conflict_id')['type_of_conflict'].nunique().unique()

array([1])

In [33]:
df.groupby('conflict_id')['gwno_loc'].nunique().unique()

array([1])

In [34]:
df.groupby('conflict_id')['gwno_a'].nunique().unique()

array([1])

In [35]:
df.groupby('conflict_id')['gwno_a_2nd'].nunique().unique()

array([ 0,  2,  1, 10,  3,  5, 13,  4, 12,  6])

In [36]:
df.groupby('conflict_id')['gwno_b'].nunique().unique()

array([0, 1])

In [37]:
df.groupby('conflict_id')['gwno_b_2nd'].nunique().unique()

array([0, 1, 3, 2, 4])

In [38]:
df.groupby('conflict_id')['side_a'].nunique().unique()

array([1])

In [39]:
df.groupby('conflict_id')['side_a_id'].nunique().unique()

array([1])

In [40]:
df.groupby('conflict_id')['side_b'].nunique().unique()

array([ 3,  1,  6,  9,  4,  8,  2, 15, 10, 12, 14, 24,  7, 17, 19,  5, 16])

In [41]:
df.groupby('conflict_id')['side_b_id'].nunique().unique()

array([ 3,  1,  6,  9,  4,  8,  2, 15, 10, 12, 14, 24,  7, 17, 19,  5, 16])

create conflict_df table

note: will later merge in the following multivalued variables:

- region
- location / gwno_loc

In [42]:
conflict_df = df[['conflict_id', 'type_of_conflict', 'start_date', 'start_prec', 'end_date', 'incompatibility_isTerritory', 'incompatibility_isGovernment', 'territory_name']].drop_duplicates().reset_index(drop=True)
conflict_df

conflict_id type_of_conflict start_date  start_prec   end_date  \
0            200         Internal 1946-07-18           1 1967-10-16   
1            201    Extrasystemic 1946-08-31           3 1953-11-09   
2            202         Internal 1946-12-31           7 1949-12-08   
3            203         Internal 1946-03-31           4 1949-10-16   
4            204    Extrasystemic 1945-10-13           2 1949-08-15   
..           ...              ...        ...         ...        ...   
281        14268         Internal 2016-08-15           1 2017-06-11   
282        14275         Internal 2016-06-01           1        NaT   
283        14333         Internal 2015-03-18           1 2016-11-09   
284        14113         Internal 2017-02-04           1        NaT   
285        14609       Interstate 2018-02-10           1        NaT   

     incompatibility_isTerritory  incompatibility_isGovernment territory_name  
0                              0                             1            NaN  
1                              1                             0       Cambodia  
2                              0                             1            NaN  
3                              0                             1            NaN  
4                              1                             0      Indonesia  
..                           ...                           ...            ...  
281                            1                             0  Islamic State  
282                            1                             0  Islamic State  
283                            1                             0  Islamic State  
284                            1                             0  Islamic State  
285                            0                             1            NaN  

[286 rows x 8 columns]

## find columns that are functionally dependent on 'ep_id' to isolate conflict EPISODES

- 'start_date2'
- 'start_prec2'
- 'ep_end_date'
- 'ep_end_prec' (this column is blank, but it shouldn't be...)

In [43]:
df.columns

Index(['conflict_id', 'cumulative_intensity', 'ep_end', 'ep_end_date',
       'ep_end_prec', 'gwno_a', 'gwno_a_2nd', 'gwno_b', 'gwno_b_2nd',
       'gwno_loc', 'incompatibility', 'intensity_level', 'location', 'region',
       'side_a', 'side_a_2nd', 'side_a_id', 'side_b', 'side_b_2nd',
       'side_b_id', 'start_date', 'start_date2', 'start_prec', 'start_prec2',
       'territory_name', 'type_of_conflict', 'year', 'obs_id', 'episode',
       'ep_id', 'isInternational', 'incompatibility_isTerritory',
       'incompatibility_isGovernment', 'end_date'],
      dtype='object')

In [44]:
df.groupby('ep_id')['start_date2'].nunique().unique()

array([1])

In [45]:
df.groupby('ep_id')['start_prec2'].nunique().unique()

array([1])

In [46]:
df.groupby('ep_id')['ep_end_prec'].nunique().unique()

array([0])

In [47]:
df.groupby('ep_id')['ep_end_date'].nunique().unique()

array([1, 0])

In [48]:
df.groupby('ep_id')['isInternational'].nunique().unique()

array([1, 0, 2])

In [49]:
df.groupby('ep_id')['cumulative_intensity'].nunique().unique()

array([1, 2])

In [50]:
df.groupby('ep_id')['intensity_level'].nunique().unique()

array([1, 2])

In [51]:
df.groupby('ep_id')['side_b'].nunique().unique()

array([ 1,  4,  3,  6,  2,  5,  8,  9,  7, 11, 15, 16])

In [52]:
episode_df = df[['conflict_id', 'episode', 'ep_id', 'start_date2', 'start_prec2', 'ep_end_date', 'ep_end_prec']] \
                .sort_values(by=['conflict_id', 'episode', 'ep_end_date']) \
                .drop_duplicates(subset=['ep_id'], keep='first').reset_index(drop=True)
episode_df

conflict_id  episode    ep_id start_date2  start_prec2 ep_end_date  \
0            200        1    200-1  1946-07-21            2  1946-07-21   
1            200        2    200-2  1952-04-09            1  1952-04-12   
2            200        3    200-3  1967-03-31            3  1967-10-16   
3            201        1    201-1  1946-08-31            3  1953-11-09   
4            202        1    202-1  1946-12-31            7  1949-12-08   
..           ...      ...      ...         ...          ...         ...   
553        14129        1  14129-1  2017-12-08            2         NaT   
554        14268        1  14268-1  2017-06-11            1  2017-06-11   
555        14275        1  14275-1  2016-06-01            1         NaT   
556        14333        1  14333-1  2016-03-07            1  2016-11-09   
557        14609        1  14609-1  2018-04-29            1         NaT   

     ep_end_prec  
0            NaN  
1            NaN  
2            NaN  
3            NaN  
4            NaN  
..           ...  
553          NaN  
554          NaN  
555          NaN  
556          NaN  
557          NaN  

[558 rows x 7 columns]

## isolate polities/actors for PARTICIPANTS table

gwno, side, and side_id do not sync up, so they cannot be merged. Instead, there will be two PARTICIPANTS tables - gwID and ucdpID

In [53]:
df.columns

Index(['conflict_id', 'cumulative_intensity', 'ep_end', 'ep_end_date',
       'ep_end_prec', 'gwno_a', 'gwno_a_2nd', 'gwno_b', 'gwno_b_2nd',
       'gwno_loc', 'incompatibility', 'intensity_level', 'location', 'region',
       'side_a', 'side_a_2nd', 'side_a_id', 'side_b', 'side_b_2nd',
       'side_b_id', 'start_date', 'start_date2', 'start_prec', 'start_prec2',
       'territory_name', 'type_of_conflict', 'year', 'obs_id', 'episode',
       'ep_id', 'isInternational', 'incompatibility_isTerritory',
       'incompatibility_isGovernment', 'end_date'],
      dtype='object')

### GW IDs

In [54]:
sideA_gwno_list = df['gwno_a'].str.split(pat=", ", expand = True)
sideA_gwno = pd.concat([df['obs_id'], sideA_gwno_list], axis=1)
sideA_gwno = sideA_gwno.melt(id_vars = ['obs_id']).dropna().reset_index(drop=True)
sideA_gwno = sideA_gwno.rename(columns={'value': 'gw_id'}).drop(columns=['variable'])
sideA_gwno['side'] = "A"
sideA_gwno['role'] = "primary"
sideA_gwno

obs_id gw_id side     role
0     200-1946   145    A  primary
1     200-1952   145    A  primary
2     200-1967   145    A  primary
3     201-1946   220    A  primary
4     201-1947   220    A  primary
...        ...   ...  ...      ...
2389  420-2003     2    A  primary
2390  228-1948   660    A  primary
2391  228-1949   660    A  primary
2392  228-1948   652    A  primary
2393  228-1949   652    A  primary

[2394 rows x 4 columns]

In [55]:
sideA2_gwno_list = df['gwno_a_2nd'].str.split(pat=", ", expand = True)
sideA2_gwno = pd.concat([df['obs_id'], sideA2_gwno_list], axis=1)
sideA2_gwno = sideA2_gwno.melt(id_vars = ['obs_id']).dropna().reset_index(drop=True)
sideA2_gwno = sideA2_gwno.rename(columns={'value': 'gw_id'}).drop(columns=['variable'])
sideA2_gwno['side'] = "A"
sideA2_gwno['role'] = "secondary"
sideA2_gwno

obs_id gw_id side       role
0       229-1949   920    A  secondary
1       229-1950   900    A  secondary
2       229-1951   900    A  secondary
3       229-1952   900    A  secondary
4       229-1953   900    A  secondary
...          ...   ...  ...        ...
1667  14113-2018   640    A  secondary
1668  11347-2018   200    A  secondary
1669  14113-2018   200    A  secondary
1670  11347-2018     2    A  secondary
1671  14113-2018     2    A  secondary

[1672 rows x 4 columns]

In [56]:
sideB_gwno_list = df['gwno_b'].str.split(pat=", ", expand = True)
sideB_gwno = pd.concat([df['obs_id'], sideB_gwno_list], axis=1)
sideB_gwno = sideB_gwno.melt(id_vars = ['obs_id']).dropna().reset_index(drop=True)
sideB_gwno = sideB_gwno.rename(columns={'value': 'gw_id'}).drop(columns=['variable'])
sideB_gwno['side'] = "B"
sideB_gwno['role'] = "primary"
sideB_gwno

obs_id gw_id side     role
0      214-1946   800    B  primary
1      215-1946   200    B  primary
2      218-1948   770    B  primary
3      218-1964   770    B  primary
4      218-1965   770    B  primary
..          ...   ...  ...      ...
127  13692-2001     2    B  primary
128  14609-2018   666    B  primary
129    252-1956   220    B  primary
130  13692-2001   200    B  primary
131    252-1956   666    B  primary

[132 rows x 4 columns]

In [57]:
sideB2_gwno_list = df['gwno_b_2nd'].str.split(pat=", ", expand = True)
sideB2_gwno = pd.concat([df['obs_id'], sideB2_gwno_list], axis=1)
sideB2_gwno = sideB2_gwno.melt(id_vars = ['obs_id']).dropna().reset_index(drop=True)
sideB2_gwno = sideB2_gwno.rename(columns={'value': 'gw_id'}).drop(columns=['variable'])
sideB2_gwno['side'] = "B"
sideB2_gwno['role'] = "secondary"
sideB2_gwno

obs_id gw_id side       role
0    205-1946   365    B  secondary
1    206-1946   365    B  secondary
2    230-2015   692    B  secondary
3    230-2016   692    B  secondary
4    230-2017   692    B  secondary
..        ...   ...  ...        ...
244  371-1991   652    B  secondary
245  371-1991   640    B  secondary
246  371-1991   696    B  secondary
247  371-1991   200    B  secondary
248  371-1991     2    B  secondary

[249 rows x 4 columns]

In [58]:
gw_participants = [sideA_gwno, sideA2_gwno, sideB_gwno, sideB2_gwno]
participants_gw_df = pd.concat(gw_participants) \
                        .merge(df[['obs_id', 'conflict_id', 'year']], how='left', on='obs_id') \
                        .sort_values(['conflict_id', 'year']).reset_index(drop=True)
participants_gw_df

obs_id gw_id side     role  conflict_id  year
0       200-1946   145    A  primary          200  1946
1       200-1952   145    A  primary          200  1952
2       200-1967   145    A  primary          200  1967
3       201-1946   220    A  primary          201  1946
4       201-1947   220    A  primary          201  1947
...          ...   ...  ...      ...          ...   ...
4442  14275-2017   840    A  primary        14275  2017
4443  14275-2018   840    A  primary        14275  2018
4444  14333-2016   616    A  primary        14333  2016
4445  14609-2018   630    A  primary        14609  2018
4446  14609-2018   666    B  primary        14609  2018

[4447 rows x 6 columns]

### UCDP IDs

In [59]:
sideA_ucdp_list = df['side_a_id'].str.split(pat=", ", expand = True)
sideA_ucdp = pd.concat([df['obs_id'], sideA_ucdp_list], axis=1)
sideA_ucdp = sideA_ucdp.melt(id_vars = ['obs_id']).dropna().reset_index(drop=True)
sideA_ucdp = sideA_ucdp.rename(columns={'value': 'ucdp_id'}).drop(columns=['variable'])
sideA_ucdp['side'] = "A"
sideA_ucdp['role'] = "primary"
sideA_ucdp

obs_id ucdp_id side     role
0     200-1946      23    A  primary
1     200-1952      23    A  primary
2     200-1967      23    A  primary
3     201-1946      33    A  primary
4     201-1947      33    A  primary
...        ...     ...  ...      ...
2389  420-2003       3    A  primary
2390  228-1948     119    A  primary
2391  228-1949     119    A  primary
2392  228-1948     118    A  primary
2393  228-1949     118    A  primary

[2394 rows x 4 columns]

In [60]:
sideB_ucdp_list = df['side_b_id'].str.split(pat=", ", expand = True)
sideB_ucdp = pd.concat([df['obs_id'], sideB_ucdp_list], axis=1)
sideB_ucdp = sideB_ucdp.melt(id_vars = ['obs_id']).dropna().reset_index(drop=True)
sideB_ucdp = sideB_ucdp.rename(columns={'value': 'ucdp_id'}).drop(columns=['variable'])
sideB_ucdp['side'] = "B"
sideB_ucdp['role'] = "primary"
sideB_ucdp

obs_id ucdp_id side     role
0     200-1946     719    B  primary
1     200-1952     720    B  primary
2     200-1967     721    B  primary
3     201-1946     160    B  primary
4     201-1947     160    B  primary
...        ...     ...  ...      ...
2998  333-1985     296    B  primary
2999  333-1986     296    B  primary
3000  333-1987     296    B  primary
3001  333-1988     296    B  primary
3002  333-1984     296    B  primary

[3003 rows x 4 columns]

In [61]:
ucdp_participants = [sideA_ucdp, sideB_ucdp]
participants_ucdp_df = pd.concat(ucdp_participants) \
                            .merge(df[['obs_id', 'conflict_id', 'year']], how='left', on='obs_id') \
                            .sort_values(['conflict_id', 'year']).reset_index(drop=True)
participants_ucdp_df

obs_id ucdp_id side     role  conflict_id  year
0       200-1946      23    A  primary          200  1946
1       200-1946     719    B  primary          200  1946
2       200-1952      23    A  primary          200  1952
3       200-1952     720    B  primary          200  1952
4       200-1967      23    A  primary          200  1967
...          ...     ...  ...      ...          ...   ...
5392  14275-2018     234    B  primary        14275  2018
5393  14333-2016     110    A  primary        14333  2016
5394  14333-2016     234    B  primary        14333  2016
5395  14609-2018     114    A  primary        14609  2018
5396  14609-2018     121    B  primary        14609  2018

[5397 rows x 6 columns]

## seperate multivalued columns - location, region - that are dependent on CONFLICT_ID

### location

note - clearly the identifiers and the names are not in the same order, so they are not matching up correctly.

In [62]:
df.columns

Index(['conflict_id', 'cumulative_intensity', 'ep_end', 'ep_end_date',
       'ep_end_prec', 'gwno_a', 'gwno_a_2nd', 'gwno_b', 'gwno_b_2nd',
       'gwno_loc', 'incompatibility', 'intensity_level', 'location', 'region',
       'side_a', 'side_a_2nd', 'side_a_id', 'side_b', 'side_b_2nd',
       'side_b_id', 'start_date', 'start_date2', 'start_prec', 'start_prec2',
       'territory_name', 'type_of_conflict', 'year', 'obs_id', 'episode',
       'ep_id', 'isInternational', 'incompatibility_isTerritory',
       'incompatibility_isGovernment', 'end_date'],
      dtype='object')

In [63]:
locations = df[['conflict_id', 'gwno_loc']]
locations = locations.drop_duplicates()
locations

conflict_id  gwno_loc
0             200       145
3             201       811
11            202       710
15            203       350
19            204       850
...           ...       ...
2376        14268       630
2377        14275       840
2380        14333       616
2381        14113       432
2383        14609  630, 666

[286 rows x 2 columns]

In [64]:
location_id_list = locations['gwno_loc'].str.split(pat=", ", expand = True)
location_df = pd.concat([locations['conflict_id'], location_id_list], axis=1) \
                .melt(id_vars = ['conflict_id']).dropna() \
                .rename(columns={'value': 'gw_id'}).drop(columns=['variable']) \
                .sort_values(['conflict_id', 'gw_id']).reset_index(drop=True)
location_df

conflict_id gw_id
0            200   145
1            201   811
2            202   710
3            203   350
4            204   850
..           ...   ...
340        14268   630
341        14275   840
342        14333   616
343        14609   630
344        14609   666

[345 rows x 2 columns]

### region

In [65]:
df.columns

Index(['conflict_id', 'cumulative_intensity', 'ep_end', 'ep_end_date',
       'ep_end_prec', 'gwno_a', 'gwno_a_2nd', 'gwno_b', 'gwno_b_2nd',
       'gwno_loc', 'incompatibility', 'intensity_level', 'location', 'region',
       'side_a', 'side_a_2nd', 'side_a_id', 'side_b', 'side_b_2nd',
       'side_b_id', 'start_date', 'start_date2', 'start_prec', 'start_prec2',
       'territory_name', 'type_of_conflict', 'year', 'obs_id', 'episode',
       'ep_id', 'isInternational', 'incompatibility_isTerritory',
       'incompatibility_isGovernment', 'end_date'],
      dtype='object')

In [66]:
regions = df[['conflict_id', 'region']]
regions = regions.drop_duplicates()
regions

conflict_id region
0             200      5
3             201      3
11            202      3
15            203      1
19            204      3
...           ...    ...
2376        14268      2
2377        14275      3
2380        14333      4
2381        14113      4
2383        14609      2

[286 rows x 2 columns]

In [67]:
region_list = regions['region'].str.split(pat=", ", expand = True)
region_df = pd.concat([regions['conflict_id'], region_list], axis=1) \
                .melt(id_vars = ['conflict_id']).dropna() \
                .rename(columns={'value': 'incompatibility_region'}).drop(columns=['variable']) \
                .sort_values(['conflict_id', 'incompatibility_region']).reset_index(drop=True)

region_dict = {"1": "Europe", "2": "Middle East", "3": "Asia", "4": "Africa", "5": "Americas"}
region_df['incompatibility_region'] = region_df['incompatibility_region'].replace(region_dict)
region_df

conflict_id incompatibility_region
0            200               Americas
1            201                   Asia
2            202                   Asia
3            203                 Europe
4            204                   Asia
..           ...                    ...
295        14129                 Africa
296        14268            Middle East
297        14275                   Asia
298        14333                 Africa
299        14609            Middle East

[300 rows x 2 columns]

## Check that all columns are accounted for, put remaining variables in OBSERVATION table

In [68]:
df.columns

Index(['conflict_id', 'cumulative_intensity', 'ep_end', 'ep_end_date',
       'ep_end_prec', 'gwno_a', 'gwno_a_2nd', 'gwno_b', 'gwno_b_2nd',
       'gwno_loc', 'incompatibility', 'intensity_level', 'location', 'region',
       'side_a', 'side_a_2nd', 'side_a_id', 'side_b', 'side_b_2nd',
       'side_b_id', 'start_date', 'start_date2', 'start_prec', 'start_prec2',
       'territory_name', 'type_of_conflict', 'year', 'obs_id', 'episode',
       'ep_id', 'isInternational', 'incompatibility_isTerritory',
       'incompatibility_isGovernment', 'end_date'],
      dtype='object')

In [69]:
conflict_df.columns

Index(['conflict_id', 'type_of_conflict', 'start_date', 'start_prec',
       'end_date', 'incompatibility_isTerritory',
       'incompatibility_isGovernment', 'territory_name'],
      dtype='object')

In [70]:
episode_df.columns

Index(['conflict_id', 'episode', 'ep_id', 'start_date2', 'start_prec2',
       'ep_end_date', 'ep_end_prec'],
      dtype='object')

In [71]:
participants_gw_df.columns

Index(['obs_id', 'gw_id', 'side', 'role', 'conflict_id', 'year'], dtype='object')

In [72]:
participants_ucdp_df.columns

Index(['obs_id', 'ucdp_id', 'side', 'role', 'conflict_id', 'year'], dtype='object')

In [ ]:
location_df.columns

Index(['conflict_id', 'gw_id'], dtype='object')

In [ ]:
region_df.columns

In [ ]:
observation_df = df[['obs_id','conflict_id', 'year', 'episode', 'ep_id', 'ep_end', 'intensity_level', 'cumulative_intensity', 'isInternational']]
observation_df.columns

In [ ]:
conflict_df.to_csv("../Data/UCDP_PRIO/Wrangled/conflicts.csv", index=False, encoding='utf-8')
episode_df.to_csv("../Data/UCDP_PRIO/Wrangled/episodes.csv", index=False, encoding='utf-8')
participants_gw_df.to_csv("../Data/UCDP_PRIO/Wrangled/participants_gw.csv", index=False, encoding='utf-8')
participants_ucdp_df.to_csv("../Data/UCDP_PRIO/Wrangled/participants_ucdp.csv", index=False, encoding='utf-8')
location_df.to_csv("../Data/UCDP_PRIO/Wrangled/locations.csv", index=False, encoding='utf-8')
region_df.to_csv("../Data/UCDP_PRIO/Wrangled/regions.csv", index=False, encoding='utf-8')
observation_df.to_csv("../Data/UCDP_PRIO/Wrangled/observations.csv", index=False, encoding='utf-8')